### ISSUE TITLE
long topup execution

### ISSUE THREAD

**Issue by soichih** [brain-life/app-mrtrix3-preproc#4]
This App currently spends a long time executing topup.

![newplot](https://user-images.githubusercontent.com/923896/50871974-8ab4d700-138b-11e9-9524-c6e95dfdaa10.png)

Also, toward the end, it runs eddy and eddy_cuda seems to be broken again. We should fix it, but as it only spends 20-30mins we can probably leave it for now?

**Comment by bcmcpher** [comment]
Yeah, there's no speeding up topup for now, so the adjusted time is
necessary for that. eddy_cuda would be <10-15 min, but <30 is already
better than I expected so it's not a priority.

It might be a good test case for testing out cuda nodes on carbonate
though, just because it is closest to working.

Brent

**Comment by soichih** [comment]
@bcmcpher The graph are in hours - not in minutes. It takes 17.6 hours to run mrtirx3 on slurm2 (using Hetrick_DTI) - most of the time spent on topup. It's not normal right?

**Comment by bcmcpher** [comment]
Topup takes that long. It only runs if AP-PA data is passed, which we don't
use on basically any other data set. It was already run on the HCP data.
The only data on bl that need this step are Roberts and Hetricks.

That's why we've never encountered these run times - most of the data we're
running don't require this step.

Brent

**Comment by soichih** [comment]
Ah ok.. thanks for letting me know. I've updated the App description to include this info.

Meanwhile, I've fixed the eddy_cuda issue on gpu1 (again). It should run much faster now (if run on non-APPA mode)
